config/routes.rb
Rails.application.routes.draw do
  
  get 'tasks/mark_as_complete'
  get 'tasks/mark_as_incomplete'
  
  devise_for :users
  resources :categories
  resources :clients
  resources :projects
  resources :tasks
  
  get 'say/hello'
  
  root 'projects#index'
  
  

end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user
end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :user
  has_many :projects
  validates_presence_of :name, :company
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates_uniqueness_of :email
  
  def client_details
    "#{name} - #{company}"
  end
  
  def details
    "#{id} - #{name} - #{company} - #{email}"
  end
  
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  #before_save :generate_project_code
  before_create :generate_project_code
  before_destroy :delete_all_tasks

  belongs_to :client
  has_many :tasks
  validates_presence_of :name, :start_date, :client_id, :status
  validates_numericality_of :client_id
  validates_length_of :name, minimum: 3
  validates_uniqueness_of :name
  
  private 
  
  def generate_project_code
    self.project_code = "ABC-#{Random.rand(1000)}"
  end

  def delete_all_tasks
    Task.where('project_id = ? ', self.id).delete_all
  end
  
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  #validate :check_date
  
  def details
    "#{name} - #{due_date.strftime("%A, %d %B %Y")}"
  end
  
  private
  def check_date
    if !self.due_date.nil? && self.due_date < Project.find(self.project_id).start_date
      errors.add(:due_date, "Invalid Date, should be greater than project start date")
    end
  end
  
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :projects
  has_many :categories
  has_many :clients
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  def index
    @categories = current_user.categories
  end
  
  def new
    @category = Category.new
  end
    
  def create
    @category = Category.new(category_params)
    @category.user_id = current_user.id
    respond_to do |format|
      if @category.save
        format.js
      end
    end
   end
  
  def edit
    @category = Category.find(params[:id])
  end
    
  def update
    @category = Category.find(params[:id])
    respond_to do |format|
      if @category.update_attributes(category_params)
        format.js
      end
    end
  end
  
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    respond_to do |format|
      format.js
    end
  end
  
  private
  def category_params
    params.require(:category).permit(:name)
  end
  
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_filter :authenticate_user!
  def index
    @clients = current_user.clients
  end
  
  def new
    @client = Client.new
  end
  
  def create
    @client = Client.new(client_params)
    @client.user_id = current_user.id
    if @client.save
      redirect_to clients_path
    else
      render action: "new"
    end
  end
  
  def show
    begin
      @client = current_user.clients.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to root_url, notice: "Record Does not exist"
    end
  end
  
  def edit
    begin
      @client = current_user.clients.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to root_url, notice: "Record Does not exist"
    end
  end
  
  def update
    @client = Client.find(params[:id])
    if @client.update_attributes(client_params)
      redirect_to client_path(@client)
    else
      render action: "edit"
    end
  end
  
  def destroy
    @client = Client.find(params[:id])
    @client.destroy
    redirect_to clients_path
  end
  
  private
  def client_params
    params[:client].permit(:name, :company, :email, :website)
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!
  
  def index
    #@projects = Project.where('user_id = ?', current_user.id)
    #current_user is the user object of the user logged in 
    @projects = current_user.projects
    respond_to do |format|
      format.html
      format.xls
    end
  end
  
  def new
    @project = Project.new
  end
  
  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id
    if @project.save
      redirect_to project_path(@project.id)
    else
      render action: "new"
    end
  end
  
  def edit
    begin
      @project = current_user.projects.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to projects_path
    end
  end
  
  def update
    @project = Project.find(params[:id])
    if @project.update_attributes(project_params)
      redirect_to project_path(@project)
    else
      render action: "edit"
    end
  end
  
  def destroy
    @project = Project.find(params[:id])
    @project.destroy
    redirect_to projects_path
  end
  
  def show
    begin
      @project = current_user.projects.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to projects_path
    end
  end
  
  private 
  def project_params
    params[:project].permit(:name, :client_id, :description, :start_date, :status)
  end
  
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  
  def hello
    @client = Client.first
    @clients = Client.all
    @projects = Project.where('start_date')
  end
  
  def goodbye
    
  end
  
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  def create
    @task = Task.new(params_task)
    if @task.save
      redirect_to project_path(@task.project_id), notice: "Successfully created the task"
    end
  end
  
  def mark_as_complete
    @task = Task.find(params[:task_id])
    @task.update_attributes(is_completed: true)
    Notification.task_completed(@task).deliver!
    redirect_to :back
  end
  
  def mark_as_incomplete
    @task = Task.find(params[:task_id])
    @task.update_attributes(is_completed: false)
    Notification.task_incomplete(@task).deliver!
    redirect_to :back
  end
  
  private
  def params_task
    params.require(:task).permit(:name, :due_date, :is_completed, :project_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_form.html.erb
<%= form_for @category, remote: true do |f| %>

<label>Name:</label><br/>
<%= f.text_field :name %><br/>
<%= f.submit %>

<% end %>

app/views/categories/create.js.erb
$('#new_category').hide();
$('#category_link').show();
$('#categories').append('<li id="li_<%= @category.id %>"><%= @category.name %> <%= link_to "edit", edit_category_path(@category), remote: true %> <%= link_to "x", category_path(@category), method: :delete, data: {confirm: "Are you sure?"}, remote: true %> </li>');
$('#count').html('<%= current_user.categories.size %>');

app/views/categories/destroy.js.erb
$('#li_<%= @category.id%>').slideUp();
$('#count').html('<%= current_user.categories.size %>');

app/views/categories/edit.js.erb
$('#category_link').hide().after('<%= j render("form")%>');

app/views/categories/index.html.erb
<h3>Listing Categories <span id="count"><%= @categories.size %></span></h3>

<ul id="categories">
  <% for category in @categories %>
  <li id="li_<%= category.id %>">
    <%= category.name %>
    <%= link_to "edit", edit_category_path(category), remote: true %>
    <%= link_to "x", category_path(category), method: :delete, data: {confirm: "Are you sure?"}, remote: true %>
  </li>
  <% end %>
</ul>

<%= link_to "Add Category", new_category_path, id: "category_link", remote: true %>

app/views/categories/new.js.erb
$('#category_link').hide().after('<%= j render("form")%>');

app/views/categories/update.js.erb
$('#edit_category_<%= @category.id %>').hide();
$('#li_<%= @category.id %>').html('<li id="li_<%= @category.id %>"><%= @category.name %> <%= link_to "edit", edit_category_path(@category), remote: true %> <%= link_to "x", category_path(@category), method: :delete, data: {confirm: "Are you sure?"}, remote: true %> </li>');
$('#category_link').show();

app/views/clients/edit.html.erb
<h3>Edit Client</h3>
<%= form_for @client do |f| %>
<% if @client.errors.any? %>
<div class="error" style="color:red" >
  <h4>Form Error!!!</h4>
<ul>
  <% for msg in @client.errors.full_messages %>
    <li><%= msg %></li>
  <% end %>
</ul>
</div>
<% end %>

<label>Name:</label><br/>
<%= f.text_field :name %><br/>

<label>Company:</label><br/>
<%= f.text_field :company %><br/>

<label>Email:</label><br/>
<%= f.email_field :email %><br/>

<label>Website:</label><br/>
<%= f.text_field :website %><br/>

<%= f.submit %> or <%= link_to "List Clients", clients_path %>
<% end %>

app/views/clients/index.html.erb
<h3>Listing Clients</h3>

<% if @clients.empty? %>
 No Clients found 
<% else %>
<ul>
  <% for client in @clients %>
  <li>
    <%= client.name %>
    <%= link_to "show", client_path(client.id) %>
  </li>
  <% end %>
</ul>
<% end %>

<a href="/clients/new">Add Client (HTML) </a> <br/>
<%= link_to "Add Client", new_client_path %>

app/views/clients/new.html.erb
<h3>Add Client</h3>
<%= form_for @client do |f| %>
<% if @client.errors.any? %>
<div class="error" style="color:red" >
  <h4>Form Error!!!</h4>
<ul>
  <% for msg in @client.errors.full_messages %>
    <li><%= msg %></li>
  <% end %>
</ul>
</div>
<% end %>

<label>Name:</label><br/>
<%= f.text_field :name %><br/>

<label>Company:</label><br/>
<%= f.text_field :company %><br/>

<label>Email:</label><br/>
<%= f.email_field :email %><br/>

<label>Website:</label><br/>
<%= f.text_field :website %><br/>

<%= f.submit %> or <%= link_to "List Clients", clients_path %>
<% end %>

app/views/clients/show.html.erb
<h3><%= @client.name %></h3>
<small><%= link_to "Edit", edit_client_path(@client.id) %> | 
  <%= link_to "Delete",  client_path(@client.id), method: :delete, data: {confirm: "Are you sure?"} %>
</small>
<hr>
<strong>Company: </strong> <%= @client.company %><br/>
<strong>Email: </strong> <%= @client.email %><br/>
<strong>Website: </strong> <%= @client.website %><br/>

<h3>Projects (* <%= @client.projects.size %> *) </h3>
<ul>
  <% for project in @client.projects %>
    <li><%= project.name %></li>
  <% end %>
</ul>


<%= link_to "List Clients", clients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Demo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if user_signed_in? %>
  Welcome <%= current_user.email %> (<%= current_user.current_sign_in_ip %> ) | <%= link_to "Account Setting", edit_user_registration_path %> | <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
  <% else %>
  <%= link_to "Sign In", new_user_session_path %> | <%= link_to "Sign Up", new_user_registration_path %>
  <% end %>
  
  <%= notice %>
  <%= alert %>
  
<%= yield %>

</body>
</html>

app/views/notification/task_completed.html.erb
<p>Dear <%= @task.project.client.name %></p>
 <p>Task (<%= @task.name %>) has been completed on <%= @task.updated_at.strftime("%A, %d %B %Y") %> at <%= @task.updated_at.strftime("%H:%M %p")%> which belongs to <%= @task.project.name %></p>
<p>Regards,<br/>
	<%= @task.project.user.email %></p>
	

app/views/notification/task_completed.text.erb
Notification#task_completed

<%= @greeting %>, find me in app/views/notification/task_completed.text.erb

app/views/notification/task_incomplete.html.erb
<p>Dear <%= @task.project.client.name %></p>
 <p>Task (<%= @task.name %>) has been re opened on <%= @task.updated_at.strftime("%A, %d %B %Y") %> at <%= @task.updated_at.strftime("%H:%M %p")%> which belongs to <%= @task.project.name %></p>
<p>Regards,<br/>
	<%= @task.project.user.email %></p>

app/views/projects/edit.html.erb
<h3>Edit Project</h3>
<%= form_for @project do |f| %>
<label>Client</label><br/>
<%= f.collection_select :client_id, Client.all, :id, :name, prompt: "Select Client" %><br/>
<%# f.collection_select :attribute, DataSource, PrimaryKey, DisplayValue, options %>

<label>Name:</label><br/>
<%= f.text_field :name %><br/>

<label>Description:</label><br/>
<%= f.text_area :description, cols: 40, rows: 5 %><br/>

<label>Start Date:</label><br/>
<%= f.date_select :start_date, order:[:day,:month,:year], start_year: Date.today.year, end_year: (Date.today + 1.year).year %><br/>

<label>Status:</label><br/>
<%= f.select :status, ["new", "completed", "on-going"], prompt: "Select Status" %><br/>

<%= f.submit %>


<% end %>

app/views/projects/index.html.erb
<h3>Listing Projects</h3>
<%= link_to "Export", projects_path(format: "xls") %>

<ul>
<% for project in @projects %>
  <li><%= link_to project.name, project_path(project) %></li>
<% end %>
</ul>

<%= link_to "New Project", new_project_path %>

app/views/projects/index.xls.erb
<h3>Listing Projects</h3>

<table border="1">
	<thead>
		<tr>
			<th>Sl No</th>
			<th>Name</th>
			<th>Description</th>
			<th>Status</th>
			<th>Start Date</th>
			<th>Client Name</th>
			<th>Task Count</th>
		</tr>
	</thead>
	<tbody>
		<% @projects.each_with_index do |project, index|%>
		<tr>
			<td><%= index + 1 %></td>
			<td><%= project.name %></td>
			<td><%= project.description %></td>
			<td><%= project.status %></td>
			<td><%= project.start_date %></td>
			<td><%= project.client.try(:name)%></td>
			<td><%= project.tasks.size %></td>
		</tr>
		<% end %>
	</tbody>
	
</table>

app/views/projects/new.html.erb
<h3>Add project</h3>
<%= form_for @project do |f| %>
<label>Client</label><br/>
<%= f.collection_select :client_id, current_user.clients, :id, :name, prompt: "Select Client" %><br/>
<%# f.collection_select :attribute, DataSource, PrimaryKey, DisplayValue, options %>

<label>Name:</label><br/>
<%= f.text_field :name %><br/>

<label>Description:</label><br/>
<%= f.text_area :description, cols: 40, rows: 5 %><br/>

<label>Start Date:</label><br/>
<%= f.date_select :start_date, order:[:day,:month,:year], start_year: Date.today.year, end_year: (Date.today + 1.year).year %><br/>

<label>Status:</label><br/>
<%= f.select :status, ["new", "completed", "on-going"], prompt: "Select Status" %><br/>

<%= f.submit %>


<% end %>

app/views/projects/show.html.erb
<h3><%= @project.name %></h3>
<%= link_to "Edit", edit_project_path(@project) %> | <%= link_to "Delete", project_path(@project), method: :delete, data: {confirm: "Are you sure?"} %>
<hr>
description: <%= @project.description %><br/>
Start Date: <%= @project.start_date %><br/>
Client : <%= @project.client.try(:name) %>

<h3>Total Tasks <%= @project.tasks.size %></h3>

<div class="red" style="color:red">
<h3>Overdue Tasks</h3>
<ul>
  <% for task in @project.tasks.where('is_completed = ? AND due_date < ?', false, Date.today) %>
    <li><%= task.details %> 
        <%= link_to "Mark as complete", tasks_mark_as_complete_path(task_id: task.id) %>

		<small>(<%= time_ago_in_words(task.due_date) %>) ago</small>
	<% end %>
</ul>
</div>

<h3>Incomplete Tasks</h3>
<ul>
  <% for task in @project.tasks.where('is_completed = ? AND due_date >= ?', false, Date.today) %>
    <li><%= task.details %>
		<%= link_to "Mark as complete", tasks_mark_as_complete_path(task_id: task.id) %>
		<small>(<%= time_ago_in_words(task.due_date) %> from now) </small>
	</li>
  <% end %>
</ul>

<h3>Completed Tasks</h3>
<ul>
  <% for task in @project.tasks.where('is_completed = ?', true) %>
  <li><%= task.name %> <%= task.due_date.strftime("%A, %d %B %Y") %>
	<%= link_to "Mark as incomplete", tasks_mark_as_incomplete_path(task_id: task.id) %>
	<small><%= time_ago_in_words(task.updated_at) %> <%= task.updated_at < Time.now ? "ago" : "from now"%></small>
	</li>
	
  <% end %>
</ul>

<h3>Add Task</h3>
<%= form_for Task.new do |f| %>
<label>Name:</label><br/>
<%= f.text_field :name %><br/>

<label>Due Date:</label><br/>
<%= f.date_select :due_date %><br/>

<label>Completed?</label><br/>
<%= f.check_box :is_completed %><br/>

<%= f.hidden_field :project_id, value: @project.id %>

<%= f.submit %>
<% end %>

app/views/say/hello.html.erb
<h3><%= @client.name %></h3>
<p><%= @client.details %></p>

<h3>Total Clients - <%= @clients.size %></h3>
<ul>
  <% for client in @clients %>
    <li><%= client.details %></li>
  <% end %>
</ul>

<table border="1">
  <thead>
    <tr>
      <th>Sl No</th>
      <th>Name</th>
      <th>Company</th>
      <th>Email</th>
    </tr>
  </thead>
  <tbody>
    <% @clients.each_with_index do |client,index| %>
    <tr>
      <td><%= index + 1 %></td>
      <td><%= client.name %></td>
      <td><%= client.company %></td>
      <td><%= client.email %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<h3>Projects</h3>
<table border="1">
  <thead>
    <tr>
      <th>Sl No</th>
      <th>Name</th>
      <th>Description</th>
      <th>Start Date</th>
      <th>Client</th>
      <th>Status</th>
      <th>Total Tasks</th>
      <th>Incompleted Tasks</th>
      <th>Completed Tasks</th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each_with_index do |project,index| %>
    <tr>
      <td><%= index + 1 %></td>
      <td><%= project.name %></td>
      <td><%= project.description %></td>
      <td><%= project.start_date %></td>
      <td><%= project.client.try(:name) %></td>
      <td><%= project.status %></td>
      <td><%= project.tasks.size %></td>
      <td><%= project.tasks.where('is_completed = ?', false).size %></td>
      <td><%= project.tasks.where('is_completed = ?', true).size %></td>
    </tr>
    <% end %>
  </tbody>
</table>